### ISSUE TITLE
Treat slim as ruby

### ISSUE THREAD

**Issue by firedev** [AndrewRadev/switch.vim#25]
Hi,

Could you please treat `slim` as `ruby`? I usually do `set ft=ruby` and then `set ft=slim` after changing things. Or maybe there is a setting for that?

**Comment by AndrewRadev** [comment]
Well, what I'd do is simply copy the definitions from here: https://github.com/AndrewRadev/switch.vim/blob/master/plugin/switch.vim#L156-167.

You could just put something like this in your vimfiles:

``` vim
autocmd FileType slim let b:switch_definitions =
      \ [
      \   g:switch_builtins.ruby_hash_style,
      \   g:switch_builtins.ruby_if_clause,
      \   g:switch_builtins.rspec_should,
      \   g:switch_builtins.rspec_expect,
      \   g:switch_builtins.rspec_be_true_false,
      \   g:switch_builtins.ruby_tap,
      \   g:switch_builtins.ruby_string,
      \   g:switch_builtins.ruby_short_blocks,
      \   g:switch_builtins.ruby_array_shorthand,
      \ ]
```

The `g:switch_builtins` dictionary simply contains all of the builtins, indexed by name, which means they're easy to reuse across filetypes. In fact, you probably don't need all of them, this is what is defined for haml:

``` vim
autocmd FileType haml let b:switch_definitions =
      \ [
      \   g:switch_builtins.ruby_if_clause,
      \   g:switch_builtins.ruby_hash_style,
      \   g:switch_builtins.haml_tag_type,
      \ ]
```

If you'd like, I can add slim as a built-in, and just copy the haml builtins. This is the documentation for them: https://github.com/AndrewRadev/switch.vim/blob/master/doc/switch.txt#L381-406. Since I haven't used slim in a while, do you think these would be enough? I've started writing some slim on a project occasionally, and I noticed there's stuff like `=>` for leaving extra whitespace, for instance. So maybe it would make sense to do something slim-specific.

Thoughts?

**Comment by firedev** [comment]
Hi, thanks, I didn't think about trying to set filetype to HAML. They are very similar and I switched to slim before I found Switch and haven't experienced HAML bindings. Let me try first.

On a side note. I am often finding myself fliping longer lines between `"double quotes"` and `'single quotes'`? With `vim-surround` but every time I try to mash minus to see if switch can do it. I do lots of refactoring of old code and do these replacements hundreds of time every day. Arguments, quotes, functions.

In fact what do you think about depending on `vim-surround` if it's installed? Detect an appropriate replacement for the current situation, say if cursor is on double quote `"` you do `ys"'` then `ys'"` to flip it back. It is probably should be a separate plugin though. Just thinking.

**Comment by firedev** [comment]
Yep it looks that `set ft=haml` is perfectly adequate for what I do at least. Guess you can merge them inside until new input comes in.

**Comment by AndrewRadev** [comment]
Done, I've pushed a commit that should re-use the haml definitions for slim.

**Comment by AndrewRadev** [comment]
Ah, yes, regarding the vim-surround stuff -- I could extend the plugin to be able to match not only on regular expressions, but also on syntax groups, for example, and then execute a normal command on it. I've been planning to do this for a while, I just haven't gotten around to it yet.

**Comment by firedev** [comment]
Thanks!
