### ISSUE TITLE
[wiki] Anyone know how to write a substitution for React props?

### ISSUE THREAD

**Issue by arthropodSeven** [AndrewRadev/switch.vim#60]
I mainly work with React. Lately, I find myself often needing to do this transform: 

```
<Thing foo={data} />
<Thing foo={`${data}`} />
```

It's very tedious even with vim-surround, and it's an ideal use-case for this plugin, but the special meanings of the characters involved have given me a headache. 

I've been slowly grinding my way up the Vim ladder since I started college in 2012. Plenty of times I've figured out how to do a regular expression that saved me hours upon hours of labor time over the course of the next months, and those are the times I'm really glad I'm obstinate enough to have stuck with it for this long, because it was a whim to begin with. 

Sometimes, though, you've just gotta ask for help. 

Can anyone write this transform? It might be a good one to add to the wiki.

**Comment by AndrewRadev** [comment]
Here's a transform that seems to work in my experiments:

``` vim
let b:switch_custom_definitions = [
      \   {
      \     '\(\k\+=\){\([[:keyword:].]\+\)}':      '\1{`${\2}`}',
      \     '\(\k\+=\){`${\([[:keyword:].]\+\)}`}': '\1{\2}',
      \   }
      \ ]
```

To break down the first pattern and its replacement:

- `\(\k\+=\)` -- 1 or more keyword characters (`\k`), grouped as `\1`
- `{\([[:keyword:].]\+\)}` -- curly bracket, followed by the group `\2` which includes 1 or more keyword chars or a `.` character (to support things like `data.property`)
- `\1{`${\2}`}` -- the first group is left untouched (it's only used to enable you to switch on the property), the second is wrapped in a `` `${}` ``

Second pattern is almost the same:

- `\(\k\+=\)` -- 1 or more keyword characters (`\k`), grouped as `\1`
- ``{`${\([[:keyword:].]\+\)}`}`` -- curly bracket, followed by a backtick and `${`, followed by the group `\2` which includes 1 or more keyword chars or a `.` character (to support things like `data.property`)
- `\1{\2}` -- the first group is left untouched (it's only used to enable you to switch on the property), the second is wrapped in a `{}` to remove the backtick string and the interpolation.

Some of these patterns might look unfamiliar, because they're vim-flavoured, like `\+` is `+` in perl-compatible regex. Try [`:help /magic`](https://vimhelp.org/pattern.txt.html#%2Fmagic) for details (yes, really, "help magic" to get regex help).

Does this make sense to you? I don't really use react often, so I don't know if this pattern would fit your use cases.

**Comment by arthropodSeven** [comment]
Huge thanks, this is extremely helpful. I'm not sure if it's an artifact of my work environment or what, but I find myself needing to do this switch a lot and it can get really time-consuming. 

Thanks for writing this plugin! It makes my life easier.

**Comment by AndrewRadev** [comment]
Thank you for the kind words :). I'll add this to the wiki and close this issue.
