### ISSUE TITLE
switch#NormalizedCase and word boundaries

### ISSUE THREAD

**Issue by Julian** [AndrewRadev/switch.vim#74]
`switch#NormalizedCase` doesn't seem to let me prevent it from matching internally in a word. Specifically, if I have [switch#NormalizedCase(['or', 'and'])](https://github.com/Julian/dotfiles/blob/7c836465b240c25a1eb39d21c957f499b795a924/.config/nvim/after/plugin/switch.vim#L10), then switch will turn `sorry` into `sandry`, but if I try `switch#NormalizedCase(['\<or\>', '\<and\>'])`, then `2 or 3` turns into `2 <and> 3` with the angle brackets carried along for the ride.

(Apologies if I've just missed it, and don't think I've ever said so but splitjoin and switch are 2 of the 3 best kept vim secrets in my opinion so super thanks for having written them!)

**Comment by AndrewRadev** [comment]
Thank you for your kind words :).

Regarding the issue, I don't think the problem is with case normalization -- in fact, if you put `['\<or\>', '\<and\>']`, I think you'll get the same result, or at least I get it locally.

The issue comes from the fact that, in a list, every item is both a pattern *and* a substitution. The code is supposed to switch from the first to the second and from the second to the first, which means `s/\<or\>/\<and\>/` and the replacement gets the `<` characters, because they're not special in the replacement part. The list version is useful for simple transformations, but doesn't work that hot when you need to use regexes.

What I can recommend in this case is using the hash form, which is basically what the plugin generates, without the `\<` parts:

``` vim
let g:switch_custom_definitions = [
      \   { '\C\<and\>': 'or', '\C\<or\>': 'and' },
      \   { '\C\<And\>': 'Or', '\C\<Or\>': 'And' },
      \   { '\C\<AND\>': 'OR', '\C\<OR\>': 'AND' },
      \ ]
```

Having said that, It feels like it'd be useful to also make a helper like `switch#NormalizedCaseWords` to also add the word boundaries. (Plus a `switch#Words` one for the same thing without case normalization). I'll try it out.

**Comment by AndrewRadev** [comment]
I've tried adding two more helper functions -- take a look, try them out, let me know what you think: https://github.com/AndrewRadev/switch.vim/blob/23243cff9000a347fc4194d3ebb511fdbb67ac05/doc/switch.txt#L201-L225

I could add one parameterized function instead, but I'd like to keep the old one for compatibility, so I've held off. Plus, the more "programmatic" of an interface I come up with, the harder it might be for someone with little Vimscript experience. 

In the future, if there's a third dimension to parameterize by, I'll introduce a common function with a dict parameter and keep the old ones as fronts.

**Comment by Julian** [comment]
> The issue comes from the fact that, in a list, every item is both a pattern and a substitution. The code is supposed to switch from the first to the second and from the second to the first, which means s/\<or\>/\<and\>/ and the replacement gets the < characters, because they're not special in the replacement part.

aaahh of course, thanks that makes total sense.

And the helpers work perfectly as well. Just put them to good use. (And probably agreed on avoiding parametrized unless there are more axes to deal with).

Thanks again for both the tip and the plugin!
